# Generated by Django 5.0.4 on 2024-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt_eTransaction",
            fields=[
                (
                    "etrasaction_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("amount", models.BigIntegerField()),
                ("rfc", models.CharField(max_length=100)),
                ("account", models.CharField(max_length=100)),
            ],
        ),
    ]
